name: Deploy

on:
  push:
    branches:
      - main  # Adjust the branch as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to server
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
      run: |
        echo "API Key: $GIPHY_API_KEY"  # Example usage, do not log your API key
        # Add your deployment script here, using the API key as necessary
